# Generated by Django 2.1.5 on 2019-01-25 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.IntegerField(unique=True)),
                ('userName', models.CharField(max_length=20, unique=True)),
                ('passWord', models.CharField(max_length=30)),
                ('nickName', models.CharField(max_length=30, unique=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=2)),
                ('personalSign', models.CharField(max_length=100)),
            ],
        ),
    ]
