# Generated by Django 2.1.5 on 2019-01-25 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_Address',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
