# Generated by Django 2.1.5 on 2019-01-25 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_user_email_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='personalSign',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
